### ISSUE TITLE
ImportError: No module named 'overrides'

### ISSUE THREAD

**Issue by float64co** [pdasigi/neural-semantic-encoders#3]
First of all thanks for open sourcing this.

Issue is as follows:

$ python3 test_nse.py 
Using Theano backend.
Traceback (most recent call last):
  File "test_nse.py", line 5, in <module>
    from nse import NSE, MultipleMemoryAccessNSE, InputMemoryMerger
  File "nse.py", line 2, in <module>
    from overrides import overrides
ImportError: No module named 'overrides'

Regards,
Luke

**Comment by erickrf** [comment]
Just install the overrides module with `pip install overrides`. It's a very simple module that provides a decorator for basic checking overriding functions.

**Comment by float64co** [comment]
Hi Erick,

Thanks for that.
I followed your suggestion around the time I asked this question and met the following error:
$ python3 test_nse.py 
Using Theano backend.
NSE reader input shape: (None, 10, 50)
NSE writer input shape: (None, 1, 100)
NSE composer input shape: (None, 100)
Traceback (most recent call last):
  File "test_nse.py", line 19, in <module>
    nse_output = nse_encoder(nse_embed_input1)  # (None, 11, 50)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 569, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 164, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/luke/src/python/neural-semantic-encoders/nse.py", line 197, in call
    mask=output_mask)
  File "/usr/local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 1090, in rnn
    go_backwards=go_backwards)
  File "/usr/local/lib/python3.5/site-packages/theano/scan_module/scan.py", line 745, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/usr/local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 1082, in _step
    output, new_states = step_function(input, states)
  File "/home/luke/src/python/neural-semantic-encoders/nse.py", line 173, in compose_and_write_step
    mem_tm1 = K.reshape(flattened_mem_tm1, mem_tm1_shape)  # (batch_size, input_length, output_dim)
  File "/usr/local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 567, in reshape
    return T.reshape(x, shape)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 4541, in reshape
    rval = op(x, newshape)
  File "/usr/local/lib/python3.5/site-packages/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 4363, in make_node
    raise TypeError("Shape must be integers", shp, shp.dtype)
TypeError: ('Shape must be integers', MakeVector{dtype='float64'}.0, 'float64')


Any idea what's up? (python3 after running 2to3 -w on the repo).

Regards,
Luke

**Comment by erickrf** [comment]
No idea. I'm stuck with the same error as reported in #2 . I'll try to fork it and fix some of the code.
